### ISSUE TITLE
Describe option to specify PreParser explicitly

### ISSUE THREAD

**Issue by jfingerh** [p4lang/pna#25]
This was discussed a fair amount around Jan 2021, and there are some notes on at least some ideas on how this could be done from that time in the meeting notes from then.

**Comment by jafingerhut** [comment]
Closing this issue without any further action, as it is only relevant for the same reasons that the 2-parser vs. 1-parser PNA variant were, which is also being abandoned, as for this PR: https://github.com/p4lang/pna/pull/51
